/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsCacheOptions {
  maxMemoryMb: number
  dbPath: string
}
export declare class JsCache {
  constructor(options: JsCacheOptions)
  set(key: string, value: Buffer, ttlMs?: number | undefined | null): void
  get(key: string): Buffer | null
  delete(key: string): void
}
